### ISSUE TITLE
Calibration Issue

### ISSUE THREAD

**Issue by drcsh7002** [perfanalytics/pose2sim#141] opened 2024-10-29 07:53 UTC
when I set both the  ['calibration']['calculate']['extrinsics']['board'] to False, the Pose2Sim will show error,
![Uploading 微信截图_20241029155258.png…]()

**Comment by davidpagnon** [comment] 2024-10-30 06:31
Hi, sorry I'm away from my computer for a few days and I cannot see your screenshot. Can you upload it again?

**Comment by drcsh7002** [comment] 2024-10-30 06:54
![ERROR](https://github.com/user-attachments/assets/56d941fd-923f-4262-80df-e1db53d8c8bf)

**Comment by drcsh7002** [comment] 2024-10-30 06:56
Thank you for replying to me. I am using your pose2sim to make a small tool that can process my own experimental data. This problem makes me unable to continue

**Comment by davidpagnon** [comment] 2024-10-30 08:25
I'm not sure what you set to False, can you send me a screenshot of the calibration section of your Config.toml file?

**Comment by drcsh7002** [comment] 2024-10-30 08:34
I'm using the Pose2Sim 0.8.4
![error2](https://github.com/user-attachments/assets/495a1fc8-828c-4abe-94e8-92b2eca8678f)

**Comment by davidpagnon** [comment] 2024-11-03 19:16
Hi, thanks for the screenshot. I still don't know what the problem is. Can you first update Pose2im with `pip install pose2sim -U`?
You are telling me that setting show_reprojection_error to false leads to an error when you also set calibration_type to 'calculate' and extrinsics_method to "board". Do you get this error with extrinsics_method set to 'scene' (in the Demo trials for example)?

**Comment by davidpagnon** [comment] 2024-11-03 19:22
Okay I could reproduce the error. Let me investigate it

**Comment by davidpagnon** [comment] 2024-11-03 20:39
Okay, I found and fixed the error!
I'll wait for a bit more edits to the code to push a new release, but in the meantime you can do `pip show pose2sim` to find your installation location, look for calibration.py, and edit line 694. Replace 
```python
                imgp, objp = findCorners(img_vid_files[0], extrinsics_corners_nb, objp=object_coords_3d, show=show_reprojection_error)
```
by:

```python
                imgp = findCorners(img_vid_files[0], extrinsics_corners_nb, objp=object_coords_3d, show=show_reprojection_error)
                objp = object_coords_3d
```

**Comment by davidpagnon** [comment] 2024-11-13 14:18
I'm closing it as I believe the issue is fixed (will be added in a future release), but don't hesitate to reopen the issue if needed.

**Closed by davidpagnon** 2024-11-13 14:18 UTC
Labels: bug
